### ISSUE TITLE
AUTOPATH Plugin doesn't work right

### ISSUE THREAD

**Issue by odelphi** [Sognus/EDMC-Autopath#1]
I install the AUTOPATH plugin into the EDMC plugin directory, which is not under the EDMC directory. Then when I start EDMC, the program seems to start (it shows in task manager) but I get no client GUI at the bottom right of my screen; therefore, I cannot stop the EDMC program.  I have to go into task manager and end the program that way.  As soon as I delete the AUTOPATH plugin from the plugin directory, the EDMC GUI will show again.  I am using EDMC version 3.41 and Windows 10.

**Comment by Sognus** [comment]
After extensive testing on multiple windows versions I was unable recreate issue you have. 

Please make sure you have:
- Plugin located in EDMC plugin folder (default: [DRIVE]:\Users\[User]\AppData\Local\EDMarketConnector\plugins\EDMC-Autopath-1.0.0)
- Plugin contains following files autopath.py, load.py, plotter.py and folder pyperclip (required library)
- Plugin was enabled, previously mentioned files got their *.pyo counterparts

Please use https://pastitude.com/ or similar site (with atleast a week time limit - unlimited advised) to send content of **%temp%/EDMarketConnector.log** so I can see if there is error.

New version (support of road to riches and other things) is in work, Issue might be fixed for you in new version.

**Comment by Listatta** [comment]
I have your plugin downloaded and extracted in the download folder of windows 10, but not copy and pasted anywhere YET. 

I just followed your path/file location of `[DRIVE]:\Users[User]\AppData\Local\EDMarketConnector\plugins\EDMC-Autopath-1.0.0` and got to the plugins folder which is EMPTY. There is no EDMC-Autopath-1.0.0, there is no autopath.py, load.py, plotter.py and folder pyperclip.
![image](https://user-images.githubusercontent.com/15005546/61677471-aa22aa00-acb4-11e9-9de4-d05ef1e38eeb.png) if you intend us to extract the zip folder to that location, those directions need to be written as a step or if you intend for us to create the folder EDMC-Autopath-1.0.0 then that needs to be written as a step too. 

(also please note that using - and . in a file and folder location is bad form, while windows has made leaps and bounds on the operating system file naming flexibility, we really shouldn't push it and . should only be used as an indicator of the beginning of the file extension type such as EDMarketConnector.exe , note that he even drops the spaces between the words, yes there is a reason for that.)

Now there is a plugins folder (`C:\Program Files (x86)\EDMarketConnector\plugins`) that does have a few files in it: 
![image](https://user-images.githubusercontent.com/15005546/61677614-1f8e7a80-acb5-11e9-9bcf-62125d8263be.png)
which is where EDMarketConnector.exe installs at `C:\Program Files (x86)\EDMarketConnector`
![image](https://user-images.githubusercontent.com/15005546/61677691-56fd2700-acb5-11e9-8e2b-a13e63b8465b.png)

I just downloaded and installed ED Market Connector 2 or 3 days ago on a fresh install of ED and my usual ED applications of captain's log 2, EDDiscovery, ED Profiler, and TCE. I am running Windows 10 Pro, 1903, build#18362.239 for USA on an intel i5-6400T @2.20GHZ on 16GB RAM (windows pro is 64 bit)

SO, I think we need clarification on WHICH plugin folder you intend for it to be installed on and I think you may have an old or custom install of the EDMarket Connector because your file locations are backwards from what we've experienced??? or maybe I'm just getting totally confused on which plugins folder you are referring to (see bottom paragraphs).

Now you asked for the `%temp%/EDMarketConnector.log` info, so here you go, but like I said I've not extracted or copy and pasted your files anywhere YET

```
E:D Market Connector 3.4.2.0 2019-07-21T20:04:32
loading plugin coriolis from "C:\Program Files (x86)\EDMarketConnector\plugins\coriolis.py"
loading plugin eddb from "C:\Program Files (x86)\EDMarketConnector\plugins\eddb.py"
loading plugin eddn from "C:\Program Files (x86)\EDMarketConnector\plugins\eddn.py"
loading plugin edsm from "C:\Program Files (x86)\EDMarketConnector\plugins\edsm.py"
loading plugin edsy from "C:\Program Files (x86)\EDMarketConnector\plugins\edsy.py"
loading plugin inara from "C:\Program Files (x86)\EDMarketConnector\plugins\inara.py"
Traceback (most recent call last):
  File "companion.pyo", line 373, in query
  File "requests\models.pyo", line 935, in raise_for_status
HTTPError: 422 Client Error: Unprocessable Entity for url: https://companion.orerve.net/profile
cAPI	https://companion.orerve.net/profile 422 Unprocessable Entity 
```

I would also really like to ask that you use standard full file/folder paths in your readme and install directions such as: 

`C:\Users\{username}\AppData\Local\EDMarketConnector\plugins (where {username} is your username without the brackets and C: being the drive you system is installed on) `

Type file path naming as to avoid the confusion between `C:\Users\{username}\AppData\Local\EDMarketConnector\plugins` and `C:\Program Files (x86)\EDMarketConnector\plugins` as both are EDMarketConnector plugins file folders in different locations. That little clause in the ()'s covers a majority of the "standard" exceptions most user will encounter.

**Comment by Sognus** [comment]
I have adjusted installation description. I am not sure if it's possible make describe it even easier. If you have an idea, please submit pull request with changes.

@odelphi I am assuming that with new description and thanks to post by @Listatta  plugin is working for you now. 

I am closing this issue. If issue remains, please let me know.
