### ISSUE TITLE
Not running with latest EDMC

### ISSUE THREAD

**Issue by blueeagle69** [Sognus/EDMC-Autopath#11]
Hi.

Try as I might I cannot get EDMC 4.2.3 to load the Autopath plugin.

In my plugins folder I have;

EDPS (Elite Dangerous Passport)
Hab Zone, and 
Hourly Income along with Autopath.
The first three load fine but Autopath won't.

I have the following files in the folder.
.gitignore
 blank.py
 CHANGELOG.md
 gui.py
 LICENSE
 load.py
 neutron.py
 neutronplotter.py
   <DIR>          pyperclip
 README.md
 riches.py
    <DIR>          __pycache__

Any help would be appreciated.

Thanks.

**Comment by Sognus** [comment]
Hello,

Autopath did not support python 3 version of EDMC (version 4.0 and newer). I took a liberty to include python 3 support made   [Alberth Matos], (https://github.com/amatos), instead trying to create new rewrite from scratch I don't currently have time for - it is planned tho.

Please try recently drafted release [1.1.2](https://github.com/Sognus/EDMC-Autopath/releases/tag/V1.1.2). It should be working - passed all internal tests. Please take a note that due to changes in EDMC 4.0+ you might experience slight visual issues when changing EDMC's  theme. 

If there are further issues. Please reply to this thread.

**Comment by blueeagle69** [comment]
Awesome.

Dropped 1.1.2 into EDMC and it loaded it fine 😁

Thank you 😊
